### ISSUE TITLE
VideoJS Element is not loading the example streams

### ISSUE THREAD

**Issue by cbellosoto** [hugomods/video-js#31]
When attempting to run the exampels in the Hugo VideoJS site it is not working with the examples provided. 
https://hugomods.com/docs/media/video-js/#videojs-hls-example
https://hugomods.com/docs/media/video-js/#videojs-mpeg-dash-example

In my .md the regular video is loading fine but no the stream.

//working fine
{{< video-js "https://heishenhua.com/video/preview/video_PV03_Music.mp4" >}}

//not working
{{< video-js
  src="https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_dv_atmos/main.m3u8"
  type="application/x-mpegURL"
>}}

![image](https://github.com/hugomods/video-js/assets/40377202/a5220194-0917-4794-9bdd-fe2e8524f3f4)

Let me know if more information is needed or if the issue is just me.

**Comment by razonyang** [comment]
Does it work on the docs site? Is there any error on Chrome _Console_ tab?

**Comment by razonyang** [comment]
It would be better if you can provide a public repo for reproducing this issue.

**Comment by cbellosoto** [comment]
Yes it is working in the Doc Site.
https://hugomods.com/docs/media/video-js/

And here is my repo https://github.com/cbellosoto/TestSite/blob/main/content/index.md

Let me know if you have any questions.

**Comment by razonyang** [comment]
There are several issues:

1. Your theme doesn't implement the HugoPress, you've to include the [CSS](https://hugomods.com/docs/media/video-js/#include-the-css) and [JavaScript](https://hugomods.com/docs/media/video-js/#include-the-javascript) on your templates, tweak your template and check the page's source code.
![image](https://github.com/hugomods/video-js/assets/17720932/b7be00ab-5759-438b-81c8-6e252138f13c)
2. You're copying the source code to your own project, please kind in mind that you're maintaining the code yourself, you won't got updated if there is bugfix on this repo.
3. Please append `-D` flag on `hugo server` to build `draft` content.

**Comment by razonyang** [comment]
Closed per above comment.
